# Generated by Django 4.2.11 on 2024-05-10 06:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_requests", "0002_userrequest_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userrequest",
            name="approved",
        ),
        migrations.AddField(
            model_name="userrequest",
            name="survey_status",
            field=models.CharField(
                choices=[("P", "Pending"), ("A", "Approved"), ("R", "Rejected")],
                default="P",
                max_length=1,
            ),
        ),
    ]
