# Generated by Django 4.2.11 on 2024-05-10 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_requests', '0003_remove_userrequest_approved_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrequest',
            name='document',
        ),
        migrations.RemoveField(
            model_name='userrequest',
            name='medical_document',
        ),
        migrations.AddField(
            model_name='userrequest',
            name='aadhar_no',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='userrequest',
            name='ration_no',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
