# Generated by Django 4.2.11 on 2024-05-10 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_requests', '0004_remove_userrequest_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequest',
            name='aadhar_no',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='ration_no',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
