# Generated by Django 4.2.11 on 2024-04-10 16:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("grievance", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="grievance",
            name="survey_id",
        ),
    ]
