# Generated by Django 4.2.11 on 2024-04-08 07:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("survey", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="survey",
            old_name="request",
            new_name="request_id",
        ),
    ]
