# Generated by Django 4.2.11 on 2024-03-30 07:36

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="address",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female"), ("N", "Not Specified")],
                default="N",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="govt_id",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, null=True, region=None, unique=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="pincode",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="position",
            field=models.CharField(
                choices=[("V", "Victims"), ("W", "Ward Member"), ("C", "Collector")],
                default="V",
                max_length=1,
            ),
        ),
    ]
