# Generated by Django 4.2.11 on 2024-04-13 15:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_address_user_gender_user_govt_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_completed",
            field=models.BooleanField(default=False),
        ),
    ]
